version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: grafolana-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: grafolana
      POSTGRES_PASSWORD: grafolana_dev
      POSTGRES_DB: grafolana
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafolana"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - grafolana-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: grafolana-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - grafolana-network

volumes:
  postgres_data:
    name: grafolana_postgres_data
  pgadmin_data:
    name: grafolana_pgadmin_data

networks:
  grafolana-network:
    name: grafolana-network