version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: grafolana-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: grafolana
      POSTGRES_PASSWORD: grafolana_dev
      POSTGRES_DB: grafolana
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafolana"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: grafolana_postgres_data